import pathlib

days_dir = pathlib.Path("Days")
output_file = pathlib.Path("all_days.md")

# sort by filename (Day001.md → Day002.md …)
files = sorted(days_dir.glob("*.md"))

with output_file.open("w", encoding="utf-8") as out:
    # auto-generated note
    out.write("<!-- Auto-generated by GitHub Actions. Do not edit directly. -->\n\n")
    out.write("# All Days Combined\n\n")

    for i, f in enumerate(files, start=1):
        out.write(f"# {f.stem}\n\n")  # filename as heading
        out.write(f.read_text(encoding="utf-8"))
        out.write("\n\n")
        if i != len(files):
            out.write("### Day Separator\n\n")
